services:
  - ComposePost

interferences:
  # Units: core
  cpu: 0
  # Units: MiB
  mem: 0

# Units: requests per min
workloads:
  ComposePost: !QPS!

# Units: ms
slas:
  ComposePost: !SLA!


pod_spec:
  cpu_size: 2.0
  mem_size: 2000Mi

nodes:
- node_1
- node_2
- node_3

parts: 2

cluster_status:
  - node: "node_1"
    CPU_used: 0
    mem_used: 0
    CPU_aloc: 0
    mem_aloc: 0
    CPU_cap: 40
    mem_cap: 160000
  - node: "node_2"
    CPU_used: 0
    mem_used: 0
    CPU_aloc: 0
    mem_aloc: 0
    CPU_cap: 40
    mem_cap: 160000
  - node: "node_3"
    CPU_used: 0
    mem_used: 0
    CPU_aloc: 0
    mem_aloc: 0
    CPU_cap: 40
    mem_cap: 160000