services:
  - ComposePost
  - UserTimeline
  - HomeTimeline

interferences:
  # Units: core
  cpu: 0.4
  # Units: MiB
  mem: 800

# Units: requests per min
workloads:
  ComposePost: 700
  UserTimeline: 700
  HomeTimeline: 700

# Units: ms
slas:
  ComposePost: 200
  UserTimeline: 200
  HomeTimeline: 200
