data_path: Sep17_data_social
figure_path: Sep17_data_social/figures
yaml_repo_path: yamlRepository/socialNetwork
namespace: social-network
app_img: nicklin9907/erms:socialnetwork-1.1
nodes_for_test:
- izj6c6vb9bfm8mxnvb4n44z
- izj6c6vb9bfm8mxnvb4n45z
- izj6c6vb9bfm8mxnvb4n46z
- izj6c6vb9bfm8mxnvb4n47z
prometheus_host: http://localhost:30090
nodes_for_infra:
- izj6c4ghaaduar69lb5hlsz
pod_spec:
  cpu_size: 2
  mem_size: 2048Mi

replicas:
  ComposeReview:
    nginx-web-server: 1
    compose-review-service: 1
    movie-id-service: 1
  Search:
    frontend: 1
    reservation: 1
    search: 1
  Recommendation:
    frontend: 1
    profile: 1
    recommendation: 1
  ComposePost:
    nginx-thrift: 1
    compose-post-service: 1
    text-service: 1
  UserTimeline:
    nginx-thrift: 1
    user-timeline-service: 1
    post-storage-service: 1
  HomeTimeline:
    nginx-thrift: 1
    post-storage-service: 1